services:
  # Django Main Platform
  - type: web
    name: askimate-mainplatform
    env: docker
    dockerfilePath: ./AskiMate_main_platform/Dockerfile
    dockerCommand: >
      /bin/sh -c "python manage.py migrate &&
                  python manage.py collectstatic --noinput &&
                  gunicorn AskiMate_platform.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - fromGroup: askimate-env
    autoDeploy: true

  # AI App Service
  - type: web
    name: askimate-ai-app
    env: docker
    dockerfilePath: ./AskiMate_main_platform/ai_app/Dockerfile
    dockerCommand: uvicorn chat_app:app --host 0.0.0.0 --port 8000
    envVars:
      - fromGroup: askimate-env
    healthCheckPath: /health
    autoDeploy: true

# گروه متمرکز متغیرهای محیطی
envVarGroups:
  - name: askimate-env
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "change-me"
      - key: DEBUG
        value: "False"
      - key: DB_NAME
        value: "askimate_db"
      - key: DB_USER
        value: "askimate_user"
      - key: DB_PASSWORD
        value: "dmgBKRlYDbl4EyYx1ajz0dJNrT6xgUdQ"
      - key: DB_HOST
        value: "dpg-d30k7gf9dies7381el2g-a"
      - key: DB_PORT
        value: "5432"
      - key: EMAIL_HOST_USER
        value: "change-me"
      - key: EMAIL_HOST_PASSWORD
        value: "change-me"
      - key: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
        value: "change-me"
      - key: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
        value: "change-me"
      - key: AWS_REGION
        value: "change-me"
      - key: BEDROCK_ENDPOINT
        value: "change-me"
      - key: AWS_ACCESS_KEY_ID
        value: "change-me"
      - key: AWS_SECRET_ACCESS_KEY
        value: "change-me"
