services:
  - type: web
    name: aski-mate-main-platform
    env: python
    plan: free
    autoDeploy: true
    buildCommand: "./build.sh"
    startCommand: "gunicorn AskiMate_main_platform.wsgi:application --bind 0.0.0.0:8000"
    envVarGroups:
      - name: askimate-env

envVarGroups:
  - name: askimate-env
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "${DJANGO_SECRET_KEY}"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "askimate-ai.onrender.com,askimateai.com,www.askimateai.com"
      - key: AWS_REGION
        value: "us-east-1"
      - key: AWS_ACCESS_KEY_ID
        value: "${AWS_ACCESS_KEY_ID}"
      - key: AWS_SECRET_ACCESS_KEY
        value: "${AWS_SECRET_ACCESS_KEY}"
      - key: DB_NAME
        value: "askimate_db"
      - key: DB_USER
        value: "askimate_user"
      - key: DB_PASSWORD
        value: "${DB_PASSWORD}"
      - key: DB_HOST
        value: "dpg-d30k79fdiees7381el2g-a.oregon-postgres.render.com"
      - key: DB_PORT
        value: "5432"
      - key: EMAIL_HOST_USER
        value: "${EMAIL_HOST_USER}"
      - key: EMAIL_HOST_PASSWORD
        value: "${EMAIL_HOST_PASSWORD}"
      - key: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
        value: "${SOCIAL_AUTH_GOOGLE_OAUTH2_KEY}"
      - key: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
        value: "${SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET}"
      - key: AI_API_URL
        value: "https://askimate-ai-service.onrender.com/chat/"
      - key: BEDROCK_ENDPOINT
        value: "bedrock-runtime.us-east-1.amazonaws.com"
      - key: HUGGING_FACE_TOKEN
        value: "${HUGGING_FACE_TOKEN}"
