Hugging_face:
  Model_name: "meta-llama/Llama-3.1-8B-Instruct"
  Hugging_face_token: ${HUGGING_FACE_TOKEN}

AWS:
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  region: "us-east-1"
  model_id: "arn:aws:bedrock:us-east-1:128303994631:inference-profile/us.meta.llama3-1-8b-instruct-v1:0"
