# Generated by Django 5.2.4 on 2025-09-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_rename_content_chatmessage_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='detected_language',
            field=models.CharField(blank=True, help_text='Detected language of the message', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='original_message',
            field=models.TextField(blank=True, help_text='Original message before translation', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='translated_message',
            field=models.TextField(blank=True, help_text='Translated message', null=True),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='user_language',
            field=models.CharField(default='English', help_text='User preferred language', max_length=50),
        ),
    ]
