# Generated by Django 5.2.4 on 2025-09-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0006_chatmessage_detected_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_translated',
            field=models.BooleanField(default=False),
        ),
    ]
