# Generated by Django 5.2.4 on 2025-09-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_chatmessage_is_translated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='detected_language',
            field=models.CharField(blank=True, help_text='Detected language of the message', max_length=255, null=True),
        ),
    ]
