# Generated by Django 5.2.4 on 2025-09-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0008_alter_chatmessage_detected_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationsession',
            name='user_language',
            field=models.CharField(default='English', help_text='User preferred language', max_length=255),
        ),
    ]
