services:
  # Persistent PostgreSQL database
  - type: pserv
    name: askimate-db
    env: docker
    image: postgres:15
    plan: standard
    envVars:
      - key: POSTGRES_DB
        value: ${DB_NAME}
      - key: POSTGRES_USER
        value: ${DB_USER}
      - key: POSTGRES_PASSWORD
        value: ${DB_PASSWORD}
    disk:
      name: postgres_data
      mountPath: /var/lib/postgresql/data
    ports:
      - port: 5432
    autoDeploy: false

  # Django Main Platform
  - type: web
    name: askimate-mainplatform
    env: docker
    dockerfilePath: ./mainplatform/Dockerfile
    dockerCommand: >
      /bin/sh -c "python manage.py migrate &&
                  python manage.py collectstatic --noinput &&
                  gunicorn AskiMate_platform.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - fromGroup: askimate-env
      - key: DJANGO_SETTINGS_MODULE
        value: AskiMate_platform.settings
      - key: DB_HOST
        value: askimate-db
      - key: DB_PORT
        value: "5432"
    autoDeploy: true

  # AI App Service
  - type: web
    name: askimate-ai-app
    env: docker
    dockerfilePath: ./ai_app/Dockerfile
    dockerCommand: uvicorn chat_app:app --host 0.0.0.0 --port 8000
    envVars:
      - fromGroup: askimate-env
      # اگر AI App به DB لازم نداره، این دو خط رو حذف کن
      - key: DB_HOST
        value: askimate-db
      - key: DB_PORT
        value: "5432"
    healthCheckPath: /health
    autoDeploy: true

# گروه متمرکز متغیرهای محیطی
envVarGroups:
  - name: askimate-env
    envVars:
      # Django settings
      - key: DJANGO_SECRET_KEY
        value: "change-me"
      - key: DEBUG
        value: "False"

      # Database
      - key: DB_NAME
        value: "change-me"
      - key: DB_USER
        value: "change-me"
      - key: DB_PASSWORD
        value: "change-me"

      # Email
      - key: EMAIL_HOST_USER
        value: "change-me"
      - key: EMAIL_HOST_PASSWORD
        value: "change-me"

      # Google OAuth2
      - key: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
        value: "change-me"
      - key: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
        value: "change-me"

      # AWS / Bedrock (برای AI App)
      - key: AWS_REGION
        value: "change-me"
      - key: BEDROCK_ENDPOINT
        value: "change-me"
      - key: AWS_ACCESS_KEY_ID
        value: "change-me"
      - key: AWS_SECRET_ACCESS_KEY
        value: "change-me"
